name: Upload Files to S3

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up AWS credentials using Access Key and Secret Key
    - name: Set up AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # GitHub Secrets for AWS Access Key
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # GitHub Secrets for AWS Secret Key
        AWS_REGION: us-east-1  # Specify the region of your S3 bucket
      run: |
        echo "AWS credentials configured successfully"

    # Step 3: Upload all files to the specified S3 bucket using AWS S3 sync without AWS CLI
    - name: Upload files to S3 using S3 API (no AWS CLI)
      run: |
        curl -X POST -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -H "x-amz-security-token: ${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -d '{"Bucket": "my-unique-bucket-name-1989", "Key": "your-file-name", "Body": "file-content"}' \
          https://s3.amazonaws.com
